### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by bixiang** [ZikangZhou/QCNet#4]
Hi, your work is great. I try to generate the prediction results on the test set by following your code:
```
python test.py --model QCNet --root /path/to/dataset_root/ --ckpt_path /path/to/your_checkpoint.ckpt
```
But there is some error like this:
```
Global seed set to 2023
Processing...
  0%|          | 0/24984 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "test.py", line 40, in <module>
    test_dataset = {
  File "/content/QCNet/datasets/argoverse_v2_dataset.py", line 150, in __init__
    super(ArgoverseV2Dataset, self).__init__(root=root, transform=transform, pre_transform=None, pre_filter=None)
  File "/usr/local/envs/QCNet/lib/python3.8/site-packages/torch_geometric/data/dataset.py", line 97, in __init__
    self._process()
  File "/content/QCNet/datasets/argoverse_v2_dataset.py", line 534, in _process
    self.process()
  File "/content/QCNet/datasets/argoverse_v2_dataset.py", line 190, in process
    map_data = read_json_file(map_path)
TypeError: object() takes no arguments
```
Wondering what's the reason and how to deal with it. Thank you very much.

**Comment by ZikangZhou** [comment]
It seems that you haven’t installed the av2 api. Could you confirm whether the av2 package has been installed in your current environment?

**Comment by ZikangZhou** [comment]
Could you "import av2" successfully?

**Comment by shahaamirbader** [comment]
I was facing the same issue. This got resolved using "pip install av2".

**Comment by bixiang** [comment]
@ZikangZhou Thank you. I have solved the error I mentioned and run test on a 24GB card, but there is a new error:
![image](https://github.com/ZikangZhou/QCNet/assets/13329765/3c928a8c-d238-44d4-952c-391be07aa631)
@shahaamirbader Did you have the same problem?

**Comment by shahaamirbader** [comment]
Hi I haven't yet faced this error since presently I am training this model. I may face this issue during test as you are facing. By the way how long did it take for you to train the network? I have 2 GPUs , 32 GB and it's been two days and only 7 epochs. Do you know if the author has shared the checkpoints of the retrained models?

**Comment by ZikangZhou** [comment]
> @ZikangZhou Thank you. I have solved the error I mentioned and run test on a 24GB card, but there is a new error: ![image](https://user-images.githubusercontent.com/13329765/254461503-3c928a8c-d238-44d4-952c-391be07aa631.png) @shahaamirbader Did you have the same problem?

This is because you're using an old version of av2-api. To avoid re-installing av2, you can try to replace the content in lib/python3.8/site-packages/av2/datasets/motion_forecasting/eval/submission.py with the latest code in https://github.com/argoverse/av2-api/blob/main/src/av2/datasets/motion_forecasting/eval/submission.py. Sorry for the inconvenience in installation.

**Comment by ZikangZhou** [comment]
> Hi I haven't yet faced this error since presently I am training this model. I may face this issue during test as you are facing. By the way how long did it take for you to train the network? I have 2 GPUs , 32 GB and it's been two days and only 7 epochs. Do you know if the author has shared the checkpoints of the retrained models?

The checkpoint can be downloaded here: https://drive.google.com/file/d/1OKBytt6N6BdRa9FWmS7F1-YvF0YectBv/view?usp=drive_link

**Comment by ZikangZhou** [comment]
@bixiang BTW, can you tell me the test set performance of the checkpoint if you can submit it to the leaderboard?

**Comment by bixiang** [comment]
@ZikangZhou Thank you very much. I have run successfully and the result on the leaderboard is:
![image](https://github.com/ZikangZhou/QCNet/assets/13329765/d0996d63-0f37-45b7-82b4-d77e9ade9b18)
A little bit worse than your submission.

**Comment by ZikangZhou** [comment]
> @ZikangZhou Thank you very much. I have run successfully and the result on the leaderboard is:
> ![image](https://user-images.githubusercontent.com/13329765/255278304-d0996d63-0f37-45b7-82b4-d77e9ade9b18.png)
> A little bit worse than your submission.

Thx! Actually this performance is better，because my previous submission has used ensembling (combination of 5 single models).

**Comment by USCT-YQJ** [comment]
> @ZikangZhou Thank you very much. I have run successfully and the result on the leaderboard is: ![image](https://user-images.githubusercontent.com/13329765/255278304-d0996d63-0f37-45b7-82b4-d77e9ade9b18.png) A little bit worse than your submission.

I submit the "submission.parquet" file into the argoverse2 eval website, but it takes a long time to get the eval result, and i haven't get the eval result until now, so what's wrong with me?

**Comment by zaplm** [comment]
@ZikangZhou Hi, Zhou! What do you mean about ensembling (combination of 5 single models)? Are those models all QCNet, or are QCNet and other models?

**Comment by ZikangZhou** [comment]
> @ZikangZhou Hi, Zhou! What do you mean about ensembling (combination of 5 single models)? Are those models all QCNet, or are QCNet and other models?

All are QCNet.

**Comment by SupOne11** [comment]
@ZikangZhou Hello, Zhou. How can the 30 trajectories generated by the 5 models be integrated into trajectories for the 6 modes?

**Comment by rongxiaoqu** [comment]
> @ZikangZhou Hello, Zhou. How can the 30 trajectories generated by the 5 models be integrated into trajectories for the 6 modes?

@ZikangZhou I am also confused how the 5 models are integrated.

**Comment by aroundabout** [comment]
> > @ZikangZhou Hello, Zhou. How can the 30 trajectories generated by the 5 models be integrated into trajectories for the 6 modes?
> 
> @ZikangZhou I am also confused how the 5 models are integrated.

@rongxiaoqu  do you have any idea about integrating 5 models now?

**Comment by zhangyong511** [comment]
> > @ZikangZhou Hi, Zhou! What do you mean about ensembling (combination of 5 single models)? Are those models all QCNet, or are QCNet and other models?
> 
> All are QCNet.

Hello, may I ask how much K you selected when using K-MEANS?

**Comment by dcspsy** [comment]
> > @ZikangZhou Thank you. I have solved the error I mentioned and run test on a 24GB card, but there is a new error: ![image](https://user-images.githubusercontent.com/13329765/254461503-3c928a8c-d238-44d4-952c-391be07aa631.png) @shahaamirbader Did you have the same problem?
> 
> This is because you're using an old version of av2-api. To avoid re-installing av2, you can try to replace the content in lib/python3.8/site-packages/av2/datasets/motion_forecasting/eval/submission.py with the latest code in https://github.com/argoverse/av2-api/blob/main/src/av2/datasets/motion_forecasting/eval/submission.py. Sorry for the inconvenience in installation.

在我的例子里，当我注释掉QCNet/datasets/argoverse_v2_dataset.py 34~43行的try...except，发现环境中opencv 的依赖库（libgthread-2.0.so.0,libGL.so.0）没有正确安装。安装后问题解决。

**Comment by dcspsy** [comment]
> Hi, your work is great. I try to generate the prediction results on the test set by following your code:
> 
> ```
> python test.py --model QCNet --root /path/to/dataset_root/ --ckpt_path /path/to/your_checkpoint.ckpt
> ```
> 
> But there is some error like this:
> 
> ```
> Global seed set to 2023
> Processing...
>   0%|          | 0/24984 [00:00<?, ?it/s]
> Traceback (most recent call last):
>   File "test.py", line 40, in <module>
>     test_dataset = {
>   File "/content/QCNet/datasets/argoverse_v2_dataset.py", line 150, in __init__
>     super(ArgoverseV2Dataset, self).__init__(root=root, transform=transform, pre_transform=None, pre_filter=None)
>   File "/usr/local/envs/QCNet/lib/python3.8/site-packages/torch_geometric/data/dataset.py", line 97, in __init__
>     self._process()
>   File "/content/QCNet/datasets/argoverse_v2_dataset.py", line 534, in _process
>     self.process()
>   File "/content/QCNet/datasets/argoverse_v2_dataset.py", line 190, in process
>     map_data = read_json_file(map_path)
> TypeError: object() takes no arguments
> ```
> 
> Wondering what's the reason and how to deal with it. Thank you very much.

在我的例子里，当我注释掉QCNet/datasets/argoverse_v2_dataset.py 34~43行的try...except，发现环境中opencv 的依赖库（libgthread-2.0.so.0,libGL.so.0）没有正确安装。安装后问题解决。

**Comment by muhammadAttaurrahman** [comment]
![test](https://github.com/ZikangZhou/QCNet/assets/53517520/a3884a59-efcb-4169-a81e-b1d688ea4890)

Hey!, great work. the data loader loads, but no further process, how to fix this issue?
